repos:
  - repo: local
    hooks:
      - id: shfmt
        name: shfmt
        language: golang
        additional_dependencies: ["mvdan.cc/sh/v3/cmd/shfmt@v3.13.0"]
        entry: shfmt --indent=4 --diff --write
        types: [shell]
