alias dc="docker"
alias doc="docker"
alias img="clear; docker images; echo; docker ps -a"
alias psa="clear; docker ps --all; echo; docker images"
alias rmi="clear; docker rmi"
alias stop="docker stop"
