# Change Directory Aliases

alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
alias desktop="cd ~/Desktop"
alias dt="desktop"
alias documents="cd ~/Documents"
alias downloads="cd ~/Downloads"
alias dl="downloads"
alias library="cd ~/Library"
alias movies="cd ~/Movies"
alias music="cd ~/Music"
alias p="cd ~/Projects"
alias pictures="cd ~/Pictures"
alias public="cd ~/Public"
alias tmp="cd /tmp"
alias workspace="cd ~/workspace"
alias www="cd /Library/WebServer/Documents"
alias ww="www"
